#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Junior Deogracias
"""Generate <emb/storage.h> from the layout probe (SPEC-001 §6.2, SPEC-009, ADR-006).

kernel/object/storage_probe.c makes the compiler write, for every object type, a marker
    ->EMB_PROBE <type> <sizeof(embk_<type>_t)> <_Alignof(embk_<type>_t)>
into the probe's object file. The marker is plain bytes, so it is read the same way
from any object format (ELF, Mach-O, COFF) and any target, without nm. The header is
written from those values, so the public storage types can never drift from the
kernel's layout.
"""
import argparse
import os
import re
import sys

MARKER = re.compile(rb"->EMB_PROBE ([a-z0-9_]+) ([0-9]+) ([0-9]+)")


def fail(msg):
    print(f"gen_storage: {msg}", file=sys.stderr)
    return 1


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("objects", nargs="+")
    args = ap.parse_args(argv)
    probes = {}
    for obj in args.objects:
        with open(obj, "rb") as f:
            data = f.read()
        for m in MARKER.finditer(data):
            name = m.group(1).decode("ascii")
            size, align = int(m.group(2)), int(m.group(3))
            if name in probes and probes[name] != (size, align):
                return fail(f"conflicting values for '{name}': {probes[name]} and {(size, align)}")
            probes[name] = (size, align)
    if "thread" not in probes:
        return fail("no probe markers found; was storage_probe.c compiled with LTO or to bitcode?")
    for name, (size, align) in probes.items():
        if size == 0:
            return fail(f"'{name}': size 0")
        if align == 0 or (align & (align - 1)) != 0:
            return fail(f"'{name}': alignment {align} is not a power of two")
        if size % align != 0:
            return fail(f"'{name}': size {size} is not a multiple of its alignment {align}")
    lines = ["/* Generated by tools/storage/gen_storage.py from the layout probe; do not edit. */",
             "/* SPDX-License-Identifier: Apache-2.0 */",
             "#ifndef EMB_STORAGE_H", "#define EMB_STORAGE_H", "",
             "#include <emb/compiler.h>", "#include <emb/types.h>", "",
             "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    for name in sorted(probes):
        up = name.upper()
        size, align = probes[name]
        lines += [f"#define EMB_{up}_STORAGE_SIZE  {size}u",
                  f"#define EMB_{up}_STORAGE_ALIGN {align}u",
                  f"typedef union emb_{name}_storage {{",
                  f"    emb_max_align_t align_;",
                  f"    unsigned char bytes_[EMB_{up}_STORAGE_SIZE] EMB_ALIGNED(EMB_{up}_STORAGE_ALIGN);",
                  f"}} emb_{name}_storage_t;", ""]
    lines += ["#ifdef __cplusplus", "}", "#endif", "", "#endif /* EMB_STORAGE_H */", ""]
    text = "\n".join(lines)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    if os.path.exists(args.out):
        with open(args.out, encoding="utf-8") as f:
            if f.read() == text:
                return 0
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
