#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Junior Deogracias
"""Generate <emb/storage.h> from the layout probe (SPEC-001 §6.2, SPEC-009, ADR-006).

kernel/object/storage_probe.c defines, for every object type, two arrays whose sizes
are sizeof and _Alignof of the real kernel object:
    embk_probe_size_<type>[sizeof(embk_<type>_t)]
    embk_probe_align_<type>[_Alignof(embk_<type>_t)]
`nm --print-size` on the compiled object reports those sizes; the header is written
from them, so the public storage types can never drift from the kernel's layout.
"""
import argparse
import os
import re
import subprocess
import sys

LINE = re.compile(r"^([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\s+\S\s+_?embk_probe_(size|align)_([a-z0-9_]+)$")


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--nm", default="nm")
    ap.add_argument("--out", required=True)
    ap.add_argument("objects", nargs="+")
    args = ap.parse_args(argv)
    sizes, aligns = {}, {}
    for obj in args.objects:
        out = subprocess.run([args.nm, "--print-size", obj], check=True, capture_output=True, text=True).stdout
        for line in out.splitlines():
            m = LINE.match(line.strip())
            if not m:
                continue
            value = int(m.group(2), 16)
            (sizes if m.group(3) == "size" else aligns)[m.group(4)] = value
    if not sizes:
        print("gen_storage: no probe symbols found; is the probe compiled with -fno-common?", file=sys.stderr)
        return 1
    lines = ["/* Generated by tools/storage/gen_storage.py from the layout probe; do not edit. */",
             "/* SPDX-License-Identifier: Apache-2.0 */",
             "#ifndef EMB_STORAGE_H", "#define EMB_STORAGE_H", "",
             "#include <emb/compiler.h>", "#include <emb/types.h>", "",
             "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    for name in sorted(sizes):
        up = name.upper()
        size, align = sizes[name], aligns.get(name, 1)
        lines += [f"#define EMB_{up}_STORAGE_SIZE  {size}u",
                  f"#define EMB_{up}_STORAGE_ALIGN {align}u",
                  f"typedef union emb_{name}_storage {{",
                  f"    emb_max_align_t align_;",
                  f"    unsigned char bytes_[EMB_{up}_STORAGE_SIZE] EMB_ALIGNED(EMB_{up}_STORAGE_ALIGN);",
                  f"}} emb_{name}_storage_t;", ""]
    lines += ["#ifdef __cplusplus", "}", "#endif", "", "#endif /* EMB_STORAGE_H */", ""]
    text = "\n".join(lines)
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    if os.path.exists(args.out) and open(args.out, encoding="utf-8").read() == text:
        return 0
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
