# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Junior Deogracias
# Board defaults for riscv32_virt. Applied before the profile fragment.
CONFIG_EMB_RV_MTIME_HZ=10000000
CONFIG_EMB_RV_CLINT_BASE=0x02000000
CONFIG_EMB_RV_IRQ_COUNT=8
CONFIG_EMB_TICK_NS=1000000
