# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Junior Deogracias
# The R-003 T1 and T2 measurement configuration (tiny profile, release build): the
# scheduler, notifications, sleep and timeouts, one semaphore type; no mutex, no trace.
# CONFIG_EMB_CHECKED is not set
# CONFIG_EMB_MUTEX is not set
# CONFIG_EMB_TRACE is not set
