# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Junior Deogracias
# Board defaults for mps2_an386. Applied before the profile fragment.
CONFIG_EMB_CM_CPU_HZ=25000000
CONFIG_EMB_CM_IRQ_COUNT=32
CONFIG_EMB_TICK_NS=1000000
