# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Junior Deogracias
# Board defaults for arduino_uno (SPEC-012 §11). Applied before the profile fragment.
CONFIG_EMB_AVR_MCU="atmega328p"
CONFIG_EMB_AVR_F_CPU=16000000
CONFIG_EMB_TICK_NS=1000000
